### ISSUE TITLE
Stored credentials, where are they saved?

### ISSUE THREAD

**Issue by oniric85** [FujiMakoto/IPS-Vagrant#16]
Hi,
I would like to know where the stored credentials for Invision Power community website are stored.
Thank you.

**Comment by FujiMakoto** [comment]
The actual login credentials are not stored anywhere. When you authenticate and opt to have your session remembered, ipsv simply retains your login session by saving and re-loading the session cookies for future requests.

You can locate the cookie jar file here:
```/usr/local/share/ipsv/session.txt```
